// <auto-generated />
using System;
using APISpaceSRM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APISpaceSRM.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230424233250_init8")]
    partial class init8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APISpaceSRM.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("employers");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileExtention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordAfterId")
                        .HasColumnType("int");

                    b.Property<int>("RecordBeforeId")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecordAfterId");

                    b.HasIndex("RecordBeforeId");

                    b.ToTable("photos");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BodySize")
                        .HasColumnType("int");

                    b.Property<int>("BodyType")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("SerServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SerServiceId");

                    b.ToTable("records");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Procent")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("services");
                });

            modelBuilder.Entity("APISpaceSRM.Models.SetService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("setServices");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.HasIndex("ServiceId");

                    b.ToTable("works");
                });

            modelBuilder.Entity("EmployerWork", b =>
                {
                    b.Property<int>("EmployersId")
                        .HasColumnType("int");

                    b.Property<int>("WorksId")
                        .HasColumnType("int");

                    b.HasKey("EmployersId", "WorksId");

                    b.HasIndex("WorksId");

                    b.ToTable("EmployerWork");
                });

            modelBuilder.Entity("ServiceSetService", b =>
                {
                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.Property<int>("SetServicesId")
                        .HasColumnType("int");

                    b.HasKey("ServicesId", "SetServicesId");

                    b.HasIndex("SetServicesId");

                    b.ToTable("ServiceSetService");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Photo", b =>
                {
                    b.HasOne("APISpaceSRM.Models.Record", "RecordAfter")
                        .WithMany("PhotoAfter")
                        .HasForeignKey("RecordAfterId")
                        .IsRequired();

                    b.HasOne("APISpaceSRM.Models.Record", "RecordBefore")
                        .WithMany("PhotoBefore")
                        .HasForeignKey("RecordBeforeId")
                        .IsRequired();

                    b.Navigation("RecordAfter");

                    b.Navigation("RecordBefore");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Record", b =>
                {
                    b.HasOne("APISpaceSRM.Models.Client", "Client")
                        .WithMany("Records")
                        .HasForeignKey("ClientId")
                        .IsRequired();

                    b.HasOne("APISpaceSRM.Models.SetService", "SetService")
                        .WithMany("Records")
                        .HasForeignKey("SerServiceId")
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SetService");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Work", b =>
                {
                    b.HasOne("APISpaceSRM.Models.Record", "Record")
                        .WithMany("Works")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APISpaceSRM.Models.Service", "Service")
                        .WithMany("Works")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EmployerWork", b =>
                {
                    b.HasOne("APISpaceSRM.Models.Employer", null)
                        .WithMany()
                        .HasForeignKey("EmployersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APISpaceSRM.Models.Work", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceSetService", b =>
                {
                    b.HasOne("APISpaceSRM.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APISpaceSRM.Models.SetService", null)
                        .WithMany()
                        .HasForeignKey("SetServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APISpaceSRM.Models.Client", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Record", b =>
                {
                    b.Navigation("PhotoAfter");

                    b.Navigation("PhotoBefore");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("APISpaceSRM.Models.Service", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("APISpaceSRM.Models.SetService", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
