name: ASP.NET Web API CI2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: windows-latest

    env:
      Solution_Name: 'APISpaceSRM.sln'  # Вкажіть ваше ім'я файлу рішення

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  # Вкажіть версію .NET 6

      # Відновлення залежностей
      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

    # Збірка проекту
      - name: Build
        run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore


      - name: List files in the repository
        run: dir
