name: Deploy ASP.NET Web API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      Solution_Name: 'APISpaceSRM.sln'  # Вкажіть ваше ім'я файлу рішення

    steps:
  
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'  # Вкажіть версію .NET 6

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.Solution_Name }} --configuration Release --output ${{ github.workspace }}/publish

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ${{ github.workspace }}/publish/
        server-dir: /user29121.realhost-free.net/wwwroot/  # Вкажіть шлях на сервері, куди мають бути розгорнуті файли
    rollback:
       runs-on: windows-latest
    if: failure()  # Виконати rollback, якщо попередній job зазнав невдачі

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build previous stable version
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Publish previous stable version
      run: dotnet publish ${{ env.Solution_Name }} --configuration Release --output ${{ github.workspace }}/rollback/

    - name: Deploy previous stable version to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ${{ github.workspace }}/rollback/
        server-dir: /user29121.realhost-free.net/wwwroot/